name: Testing stuff

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
env:
  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
  SKIP_CONDITION: ${{ contains(join(github.event.commits.*.message), '#skip') }}
  EVENT_NAME: ${{ github.event_name }}

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        run: echo "$COMMIT_MESSAGES"

      - name: event name
        run: echo "event name $EVENT_NAME"

      - name: skip contents
        run: echo "skip condition $SKIP_CONDITION"

      - name: skip tag and deploy contents
        run: echo "stad $SKIP_TAG_AND_DEPLOY"

      - if: ${{ env.SKIP_CONDITION == 'true' }}
        run: echo "this should print this, because this is true"

      - if: ${{ env.SKIP_CONDITION == 'false' }} 
        run: echo "this should not print if the value is false" 
        
      - if: ${{ env.SKIP_CONDITION == 'false' && github.event_name == 'push' }}
        run: echo "This should only print if commit doesn't have skip and its a push to main or pull request."

      - name: mock deploy
        if: ${{ env.SKIP_CONDITION == 'false' && github.event_name == 'push' }}
        run: echo "This should only print if tag and deploy is false"
  
  another_test_job:
    if: ${{ !contains(join(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: some step
        run: echo "This entire job should be skipped if tag and depoly is false"

      - name: some  other step
        run: echo "This entire job should be skipped if tag and depoly is true"
      

